### ISSUE TITLE
Registrierenformular wie Loginformular gestalten.

### ISSUE THREAD

**Issue by SrgSteak** [OKTOTV/FLUX2#215]
"Gestalten" ist was für Designer. Aber bitte. Ich schreib da mal eine Stunde dazu auf.

**Comment by kasabina** [comment]
Wenn der Designer drauf Zugriff hätte – gerne. Da Du mir aber dezidiert gesagt hast, da habe ich nichts drin rum zu pfrummeln, kannst du dir deine Stunde wohl selber verrechnen, oder aber höflicher sein.

lg

 
 
 
 Sabina Kargl-Faustenhammer,
 Studio für Multimedia und Webdesign
 

Mitglied designaustria
 


Graf-Starhemberg-Gasse 27/2
 1040 Wien
 
 t  +43/1/997 14 34
 f  +43/1/997 14 34/10
 e office@sabinakargl.at
w  http://www.sabinakargl.at

 Besuchen Sie uns auf Facebook


Von:  rs
Antworten an:  OKTOTV/FLUX2
Datum:  Donnerstag, 22. Dezember 2016 um 11:37
An:  OKTOTV/FLUX2
Cc:  Subscribed
Betreff:  [OKTOTV/FLUX2] Registrierenformular wie Loginformular gestalten. (#215)


"Gestalten" ist was für Designer. Aber bitte. Ich schreib da mal eine Stunde dazu auf.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OKTOTV/FLUX2","title":"OKTOTV/FLUX2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OKTOTV/FLUX2"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Registrierenformular wie Loginformular gestalten. (#215)"}],"action":{"name":"View Issue","url":"https://github.com/OKTOTV/FLUX2/issues/215"}}}

**Comment by SrgSteak** [comment]
Wenn du richtig hinhören würdest hättest du gehört wie ich gesagt habe: Das muss man überschreiben. Und das ist es bereits:
FLUX2/src/AppBundle/Resources/views/Default/register.html.twig
