### ISSUE TITLE
Blogüberschrift gehört übersetzt

### ISSUE THREAD

**Issue by SrgSteak** [OKTOTV/FLUX2#54]
@kasabina wo ist das/wie ist der translation key?

**Comment by kasabina** [comment]
Findest Du unter: Serie im Blogbereich (die Überschrift). Für das Wording
musst Du Susanna fragen.

lg

 
 
 
 Sabina Kargl-Faustenhammer,
 Studio für Multimedia und Webdesign
 

Mitglied designaustria
 


Graf-Starhemberg-Gasse 27/2
 1040 Wien
 
 t  +43/1/997 14 34
 f  +43/1/997 14 34/10
 e office@sabinakargl.at
<file:///Users/sabinakargl/Desktop/work/Portolio/CI_2009/Signatur/office@sab
inakargl.at> 
w  http://www.sabinakargl.at

 Besuchen Sie uns auf Facebook <http://www.facebook.com/sabinakargl>


Von:  rs <notifications@github.com>
Antworten an:  OKTOTV/FLUX2
<reply+00e8620216ce845e950c0e0c961e8655dc989ea49501bf2d92cf0000000113691b1e9
2a169ce0970034a@reply.github.com>
Datum:  Freitag, 3. Juni 2016 um 12:17
An:  OKTOTV/FLUX2 <FLUX2@noreply.github.com>
Cc:  Sabina Kargl-Faustenhammer <office@sabinakargl.at>, Mention
<mention@noreply.github.com>
Betreff:  [OKTOTV/FLUX2] Blogüberschrift gehört übersetzt (#54)


@kasabina <https://github.com/kasabina>  wo ist das/wie ist der translation
key?


You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OKTOTV/FLUX2/issues/54> , or mute the thread
<https://github.com/notifications/unsubscribe/AOhiAs1XgWjZ_rA0QtXXBsNQbf-bfZ
Lzks5qH_8egaJpZM4ItZPB> .
